/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#302f39',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        outline: '#777587',
        'tertiary-fixed': '#ffdbcc',
        'surface-container': '#f0ecf9',
        'on-tertiary-container': '#ffd2be',
        'inverse-on-surface': '#f3effc',
        'surface-tint': '#4d44e3',
        'on-primary-container': '#dad7ff',
        'on-background': '#1b1b24',
        'primary-fixed': '#e2dfff',
        'tertiary-fixed-dim': '#ffb695',
        'on-tertiary-fixed': '#351000',
        'on-secondary-fixed-variant': '#2f2ebe',
        'surface-bright': '#fcf8ff',
        'surface-variant': '#e4e1ee',
        'surface-container-high': '#eae6f4',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#e1e0ff',
        error: '#ba1a1a',
        'outline-variant': '#c7c4d8',
        'secondary-container': '#6063ee',
        'on-secondary-container': '#fffbff',
        'surface-container-highest': '#e4e1ee',
        'on-surface-variant': '#464555',
        'inverse-primary': '#c3c0ff',
        surface: '#fcf8ff',
        background: '#fcf8ff',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        primary: '#3525cd',
        'on-primary-fixed-variant': '#3323cc',
        secondary: '#4648d4',
        'on-surface': '#1b1b24',
        tertiary: '#7e3000',
        'primary-fixed-dim': '#c3c0ff',
        'on-primary-fixed': '#0f0069',
        'on-error': '#ffffff',
        'on-secondary-fixed': '#07006c',
        'error-container': '#ffdad6',
        'secondary-fixed-dim': '#c0c1ff',
        'surface-container-low': '#f5f2ff',
        'primary-container': '#4f46e5',
        'tertiary-container': '#a44100',
        'on-tertiary-fixed-variant': '#7b2f00',
        'surface-dim': '#dcd8e5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        base: '4px',
        'container-padding-mobile': '16px',
        'stack-md': '16px',
        'stack-lg': '24px',
        'container-padding-desktop': '24px',
        gutter: '16px',
        unit: '8px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'numeric-bold': ['18px', { lineHeight: '24px', fontWeight: '700' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}

