import {
  IdCard, CircleUserRound, Plus, CirclePlus, MessageSquarePlus, AlarmClock, LineChart,
  ArrowLeft, ArrowRight, ArrowUp, UserCheck, BookOpen, BarChart3, Droplet, Zap, Book, Cake,
  CalendarDays, Calendar, Phone, Megaphone, XCircle, MessageCircle, Check, CheckCircle2,
  ChevronLeft, ChevronRight, X, CloudUpload, Copy, CreditCard, Trash2, FileText, Download,
  DownloadCloud, Pencil, FilePenLine, Mail, AlertCircle, CalendarCheck, CalendarX, Smile,
  FileDown, Filter, ListFilter, MessagesSquare, Sigma, Star, Users, UserPlus, UsersRound,
  HelpCircle, History, ScrollText, Building2, Image, Inbox, Info, TrendingUp, Key, BarChart2,
  Library, Link, MapPin, Lock, KeyRound, LogOut, User, Medal, MoreVertical, Bell, BellRing,
  ExternalLink, PauseCircle, Wallet, ClipboardList, UserX, PartyPopper, Camera, PlayCircle,
  Printer, Loader2, Upload, Activity, CircleDot, RefreshCw, RotateCcw, GraduationCap, Search,
  Send, Settings, Shield, Thermometer, Smartphone, MessageSquare, MessageSquareWarning,
  Sparkles, UserCog, ArrowLeftRight, Table, TrendingDown, Minus, Trophy, SlidersHorizontal,
  FileUp, BadgeCheck, ShieldCheck, Eye, EyeOff, Volume2, AlertTriangle, Award,
  MessageSquareText, ChevronUp, ChevronDown, Flame, CheckCheck,
  Home, ClipboardCheck, LayoutDashboard, FileBarChart, Clock,
} from 'lucide-react'

// Maps the old Material Symbols names to lucide-react components so call sites
// that still pass the Material name (e.g. icon="school") keep working.
const ICONS = {
  account_box: IdCard,
  account_circle: CircleUserRound,
  add: Plus,
  add_circle: CirclePlus,
  add_comment: MessageSquarePlus,
  alarm: AlarmClock,
  analytics: LineChart,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  assessment: FileBarChart,
  assignment: ClipboardCheck,
  assignment_ind: UserCheck,
  auto_graph: LineChart,
  auto_stories: BookOpen,
  bar_chart: BarChart3,
  bloodtype: Droplet,
  bolt: Zap,
  book: Book,
  cake: Cake,
  calendar_month: CalendarDays,
  calendar_today: Calendar,
  call: Phone,
  campaign: Megaphone,
  cancel: XCircle,
  chat: MessageCircle,
  chat_bubble: MessageSquareText,
  chat_bubble_outline: MessageCircle,
  check: Check,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  cloud_upload: CloudUpload,
  content_copy: Copy,
  credit_card: CreditCard,
  dashboard: LayoutDashboard,
  delete: Trash2,
  description: FileText,
  download: Download,
  done: Check,
  done_all: CheckCheck,
  download_for_offline: DownloadCloud,
  edit: Pencil,
  edit_note: FilePenLine,
  email: Mail,
  error: AlertCircle,
  error_outline: AlertCircle,
  event: Calendar,
  event_available: CalendarCheck,
  event_busy: CalendarX,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  face: Smile,
  file_download: FileDown,
  filter_alt: Filter,
  filter_list: ListFilter,
  forum: MessagesSquare,
  functions: Sigma,
  grade: Star,
  group: Users,
  group_add: UserPlus,
  group_off: UsersRound,
  groups: Users,
  help_center: HelpCircle,
  history: History,
  home: Home,
  history_edu: ScrollText,
  hotel: Building2,
  how_to_reg: UserCheck,
  id_card: IdCard,
  image: Image,
  inbox: Inbox,
  info: Info,
  insights: TrendingUp,
  key: Key,
  leaderboard: BarChart2,
  library_books: Library,
  link: Link,
  local_fire_department: Flame,
  location_on: MapPin,
  lock: Lock,
  lock_reset: KeyRound,
  logout: LogOut,
  mail: Mail,
  man: User,
  menu_book: BookOpen,
  military_tech: Medal,
  more_vert: MoreVertical,
  notifications: Bell,
  notifications_active: BellRing,
  open_in_new: ExternalLink,
  pause_circle: PauseCircle,
  payments: Wallet,
  pending: Clock,
  pending_actions: ClipboardList,
  person: User,
  person_add: UserPlus,
  person_celebrate: PartyPopper,
  person_off: UserX,
  phone: Phone,
  photo_camera: Camera,
  picture_as_pdf: FileText,
  play_circle: PlayCircle,
  print: Printer,
  progress_activity: Loader2,
  publish: Upload,
  query_stats: Activity,
  quiz: HelpCircle,
  radio_button_checked: CircleDot,
  refresh: RefreshCw,
  restore: RotateCcw,
  school: GraduationCap,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  show_chart: LineChart,
  sick: Thermometer,
  smartphone: Smartphone,
  sms: MessageSquare,
  sms_failed: MessageSquareWarning,
  stars: Sparkles,
  supervisor_account: UserCog,
  swap_horiz: ArrowLeftRight,
  switch_account: UserCog,
  sync: RefreshCw,
  table_view: Table,
  trending_down: TrendingDown,
  trending_flat: Minus,
  trending_up: TrendingUp,
  trophy: Trophy,
  tune: SlidersHorizontal,
  upload: Upload,
  upload_file: FileUp,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  visibility: Eye,
  visibility_off: EyeOff,
  volume_up: Volume2,
  vpn_key: KeyRound,
  warning: AlertTriangle,
  woman: User,
  workspace_premium: Award,
}

/**
 * Drop-in replacement for the old `<span className="material-symbols-outlined">name</span>`.
 * `name` accepts the same Material Symbol names used across the app.
 * Size follows the element's own font-size (so existing text-* Tailwind classes still work),
 * color follows `currentColor` (so existing text-color classes still work).
 */
export default function Icon({ name, className = '', filled = false, style, size, ...rest }) {
  const Comp = ICONS[name] || HelpCircle
  return (
    <Comp
      className={className}
      style={{ width: size ?? '1em', height: size ?? '1em', ...style }}
      fill={filled ? 'currentColor' : 'none'}
      aria-hidden="true"
      {...rest}
    />
  )
}
